### PR TITLE
There's always place for more fixes

### LINKED ISSUE #797: "Missing access token" error on (too early?) user profile retrieval
**Describe the bug**
After porting Quaternion to libQuotient 0.9, I see that one-off "missing access token" error also reported on NeoChat. Apparently, the current `Connection::assumeIdentity()` code only sets the token after calling `User::load()` in `C::P::completeSetup()`.

### PR DESCRIPTION
**Pull request by KitsuneRal**
More fixes, and I also accidentally rewrote `TestOlmAccount` with futures while doing the fixes.

### CODE REVIEW

File: Quotient/connection.h [hunk 1]
```diff
@@ -495,8 +496,21 @@ class QUOTIENT_API Connection : public QObject {
     void setLazyLoading(bool newValue);
 
     //! Start a pre-created job object on this connection
-    Q_INVOKABLE BaseJob* run(BaseJob* job,
-                             RunningPolicy runningPolicy = ForegroundRequest);
+    Q_INVOKABLE BaseJob* run(BaseJob* job, RunningPolicy runningPolicy = ForegroundRequest);
+
+    //! \brief Start a pre-created job on this connection and get a job handler to it
```
Comment (TobiasFella) [inline Quotient/connection.h]: handler or handle?

Comment (KitsuneRal) [reply Quotient/connection.h]: Handle, indeed

Comment (KitsuneRal) [inline Quotient/connection.h]:
```suggestion
    //! \brief Start a pre-created job on this connection and get a job handle to it
```
