### PR TITLE
Send megolm key when there is no new olm session

### LINKED ISSUE #610: Encryption key is not sent after few days or 100 messages
**Describe the bug**

Basically this bug: https://bugs.kde.org/show_bug.cgi?id=463705

> Neochat stops sending keys for messages after few days of using E2EE.
> 
> When I'm chatting to someone with E2EE on in 1-1 chat, the chat works fine for a few days. 
> Both users can see both messages.
> 
> After 4-5 days, Neochat stops sending the encryption keys to the other participant *and* this
> can be seen in other clients too with the same account.
> 
> On Neochat, the message shows up like normal.
> On Element, both users get this message: 
> ** Unable to decrypt: The sender's device has not sent us the keys for this message. **
> 
> After logging out and logging back in to Neochat, the keys are being sent again. 
> Restarting Neochat is not enough, you have to completely log out and log back in.

We chatted with @TobiasFella on Neochat matrix channel about it. 

Basically what he thinks it might be is that there's no encryption key sent for the new megolm session that is created after one week or 100 messages.

**To Reproduce**
Steps to reproduce the behaviour, and the description of the actual result:
1. Start E2EE chat with someone, either through Element or Neochat. (In my case, this same chat was started from Element long time ago)
2. E2EE works fine for few days
3. At some point, Neochat stops sending the keys to other clients. On Neochat, you can see your messages normally. Other clients cant see your message, even on your own account.
4. Log out from Neochat
5. Log back in to Neochat
6. E2EE messages can be sent normally again from Neochat, and the error is gone.

**Expected behavior**
E2EE keys are not being sent according to Element and other clients.

Also if you think this is something trivial to fix, maybe I could give it a try? :) I am interested in learning how Matrix works, but this may be way out of my league...

### PR DESCRIPTION
**Pull request by TobiasFella**
The existing logic is slightly broken: If there is no new olm session, we don't send a megolm session, since we return early and the megolm session is only sent after the claim keys job returned.

I hope this fixes #610

### CODE REVIEW

**Comment by TobiasFella** [comment]
@Akselmo please test if this fixes your problem

**Comment by Akselmo** [comment]
Yup, this fixed it!

Tested with following:
1. Sent 104 messages, no issues reading them at other end
2. Did the same again, again no issues
3. Restarted Neochat
4. Sent one more batch of 104 messages, again no issues

File: lib/connection.cpp [hunk 1]
```diff
@@ -2442,48 +2442,55 @@ void Connection::sendSessionKeyToDevices(
                          << "to keys to claim";
         }
 
-    if (hash.isEmpty())
+    auto sendKey = [devices, this, sessionId, index, sessionKey, roomId](){
```
Comment (KitsuneRal) [inline lib/connection.cpp]:
```suggestion
    auto sendKey = [devices, this, sessionId, index, sessionKey, roomId] {
```

File: lib/connection.cpp [hunk 2]
```diff
@@ -2442,48 +2442,55 @@ void Connection::sendSessionKeyToDevices(
...
+        for (const auto& [targetUserId, targetDeviceId] : asKeyValueRange(devices)) {
+            if (!hasOlmSession(targetUserId, targetDeviceId))
+                continue;
+
+            // Noisy and leaks the key to logs but nice for debugging
+            // qDebug(E2EE) << "Creating the payload for" << targetUserId
+            //              << targetDeviceId << sessionId << sessionKey.toHex();
+            const auto keyEventJson = RoomKeyEvent(MegolmV1AesSha2AlgoKey,
+                                                    roomId, QString::fromLatin1(sessionId),
+                                                    QString::fromLatin1(sessionKey))
```
Comment (KitsuneRal) [inline lib/connection.cpp]:
```suggestion
                                                   roomId, QString::fromLatin1(sessionId),
                                                   QString::fromLatin1(sessionKey))
```

File: lib/connection.cpp [hunk 3]
```diff
@@ -2442,48 +2442,55 @@ void Connection::sendSessionKeyToDevices(
...
+                                            targetDeviceId);
+        }
+        if (!usersToDevicesToContent.empty()) {
+            sendToDevices(EncryptedEvent::TypeId, usersToDevicesToContent);
+            QVector<std::tuple<QString, QString, QString>> receivedDevices;
+            receivedDevices.reserve(devices.size());
+            for (const auto& [user, device] : asKeyValueRange(devices))
+                receivedDevices.push_back(
+                    { user, device,
+                        d->curveKeyForUserDevice(user, device) });
```
Comment (KitsuneRal) [inline lib/connection.cpp]:
```suggestion
                    { user, device, d->curveKeyForUserDevice(user, device) });
```

File: lib/connection.cpp [hunk 4]
```diff
@@ -2442,48 +2442,55 @@ void Connection::sendSessionKeyToDevices(
...
+
+            database()->setDevicesReceivedKey(roomId, receivedDevices,
+                                                sessionId, index);
```
Comment (KitsuneRal) [inline lib/connection.cpp]:
```suggestion
                                              sessionId, index);
```

**Review by KitsuneRal — COMMENTED** [review]
Thanks a lot! Below just formatting brush-ups.
