### PR TITLE
Authenticated media and animated thumbnails support

### LINKED ISSUE #685: NetworkAccessManager doesn't work with authenticating media servers
NAM doesn't know anything about access tokens and converts `mxc` URLs into unauthenticated Matrix requests - failing on media servers that enforce authenticated access.

### PR DESCRIPTION
**Pull request by KitsuneRal**
This commit implements a proxy layer (almost entirely in terms of existing facilities - `Connection::downloadFile()/DownloadFileJob` and `Connection::getThumbnail()/MediaThumbnailJob` respectively) to spare clients from having to figure out which API, old or new, they should use to retrieve media on any given homeserver. In all honesty, the code for the new API hasn't been tested yet but it's almost entirely based on the generated API classes, so nothing should go wrong because our CS API descriptions are perfect, right? :-D

Implements [MSC3916](https://github.com/matrix-org/matrix-spec-proposals/pull/3916) and, while at it, [MSC2705](https://github.com/matrix-org/matrix-spec-proposals/pull/2705] (animated thumbnails).

### CODE REVIEW

File: Quotient/avatar.cpp [hunk 1]
```diff
@@ -6,6 +6,8 @@
 #include "connection.h"
 #include "logging_categories_p.h"
 
+#include "csapi/content-repo.h"
```
Comment (TobiasFella) [inline Quotient/avatar.cpp]: required?

**Review by TobiasFella — DISMISSED** [review]
looks reasonable

File: Quotient/avatar.cpp (hunk 1 above)
Comment (KitsuneRal) [reply Quotient/avatar.cpp]: Good catch, it was needed in the interim but not anymore.
