### PR TITLE
Numerous performance enhancements in ConnectionEncryptionData

### LINKED ISSUE #888: libQuotient spending a lot of time in sqlite call
**Describe the bug**
For a week or two now, I've been noticing NeoChat freezing for a couple of seconds whenever I sent a message in a room. After some debugging in the NeoChat Matrix room, I generated a `perf` log and flame graph with `hotspot`, which indicated that `libQuotient` was spending a lot of time on `Quotient::_impl::ConnectionEncryptionData::saveDevicesList() (libQuotientQt6.so.0.9.3)`, which then went into `sqlite3`. On inspecting the size of my caches, we determined that they are larger than expected, but didn't seem *excessively* large. They recommended that I create an issue here for further debugging.

**To Reproduce**
Steps to reproduce the behavior, and the description of the actual result:
1. Open NeoChat
2. Navigate to a room
3. Type and send a message
4. Try to do any interaction with NeoChat

**Expected behavior**
NeoChat should continue to be responsive; i.e., room navigation should still work, and I should be able to start typing another message.

**Is it environment-specific?**

 - OS: Solus 4.7
 - Version of the library: 0.9.3
 - Linkage: dynamic

**Additional context**

`perf` output files:
[neochat_perf.zip](https://github.com/user-attachments/files/20428154/neochat_perf.zip)

Image

### PR DESCRIPTION
**Pull request by redstrate**
See individual commits, I fixed what I saw in Hotspot when replicating #888 and this successfully reduces a huge lag spike to a less noticeable one. The only way I think to completely fix `saveDevicesList()` is by changing the schema, or if someone tells me what data actually changes in that table. But the changes in this PR doesn't need any database muckery!

To replicate, you can use this Python script to insert garbage rows into your Quotient database:

```python
import sqlite3
import random, string

con = sqlite3.connect("your db path")

cur = con.cursor()

for x in range(5000):
    device_id = ''.join(random.sample(string.ascii_uppercase, 10))
    cur.execute("""INSERT INTO tracked_devices VALUES ('<a chosen user id>', ?, '<id>, '<key>', '<id>', '<key>`, 0, 0)""", (device_id,))
    con.commit()
```

### CODE REVIEW

**Review by KitsuneRal — APPROVED** [review]
Makes perfect sense - thanks!

File: Quotient/connectionencryptiondata_p.cpp [hunk 1]
```diff
@@ -635,9 +624,8 @@ void ConnectionEncryptionData::handleQueryKeys(const QueryKeysJob::Response& key
     handleUserSigningKeys(keys.userSigningKeys);
     checkVerifiedMasterKeys(keys.masterKeys);
     handleDevicesList(keys.deviceKeys);
-    database.commit();
-
     saveDevicesList();
+    database.commit();
```
Comment (vkrause) [inline Quotient/connectionencryptiondata_p.cpp:628]: There's one scenario now where this badly regresses with `saveDevicesLists` taking 30-60secs due to not running inside a transaction but flushing to disk in each iteraction: `checkVerifiedMasterKeys` can call `Database::setMasterKeyVerified`, which internally also uses a transaction. Attempting to create a nested transaction will however result in an error and aborting the current transaction. This is a pre-existing problem mostly, but the performance impact was previously hidden by `saveDevicesList` having its own transaction.

Comment (redstrate) [reply Quotient/connectionencryptiondata_p.cpp:628]: Thanks for the detailed explanation, I guess I didn't get it right first-try! I'll open a PR shortly.

Comment (redstrate) [reply Quotient/connectionencryptiondata_p.cpp:628]: See https://github.com/quotient-im/libQuotient/pull/908
