### PR TITLE
Fix redactions

### LINKED ISSUE #664: The redaction algorithm pulls out content entirely
**Describe the bug**
The redaction logic in libQuotient is very heavy-handed now, removing the entire `content` sub-object before trying to look through its sub-keys and ending up inserting an empty sub-object even when it should preserve some keys.

**To Reproduce**
Redact any event with preserved keys (e.g. a member event) in a libQuotient-backed client, then look at the source code of the event; observe an empty sub-object under `content` where more keys should be.

**Expected behavior**
Certain keys (e.g. `membership` for member events) should remain in the `content` sub-object, as the spec defines ([here's the list](https://spec.matrix.org/v1.7/rooms/v9/) for room version v9, e.g.).

**Is it environment-specific?**
No.

### LINKED ISSUE #665: Redacting state events makes Room object unstable
**Describe the bug**
Once a state event is redacted, the next `Connection::saveRoomState()` has every chance to fail the `isStateEvent()` assertion inside `Room::Private::toJson()`. Looking at the variables, there's a garbage pointer in `currentState` where a normal state event is expected to exist - in the entry with the same type and state key as the one redacted.

**Is it environment-specific?**
Fedora 38

### PR DESCRIPTION
**Pull request by KitsuneRal**
Upon probing beyond the most basic redaction case (message events) the library code suddenly turned out to be quite buggy; this PR addresses what I could quickly find. Most important are the first and the last commits; while fixing `processStateEvents()` I also figured that it would be quite natural to have `Event::switchOnType()` next to `Quotient::switchOnType()` (and the member call doesn't need those `clang-format off/on` instructions to make it more readable) - so I added that.

### CODE REVIEW

File: Quotient/events/event.h [hunk 1]
```diff
@@ -305,6 +305,37 @@ class QUOTIENT_API Event {
...
+    //!     },
+    //!     [](const CallEvent& callEvent) {
+    //!         // Do what's needed if eptr points to a CallEvent or any
+    //!         // class derived from it
+    //!         return 2;
+    //!     },
+    //!     3); /* the default value to return if nothing above matched */
+    //! \endcode
+    //! As the example shows, the last parameter can optionally be either
+    //! a plain returned value instead of a visitor.
```
Comment (TobiasFella) [inline Quotient/events/event.h]: Drop the "either"

**Review by TobiasFella — DISMISSED** [review]

File: Quotient/events/event.h (hunk 1 above)
Comment (KitsuneRal) [reply Quotient/events/event.h]: Thanks :)
